baseURL = 'https://mslw.github.io/meeting-website-draft/'
languageCode = 'en-us'
title = 'Title TBD'
theme = "PaperMod"

# see https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

[params]
  [params.profileMode]
    enabled = true
    # title= "<Title>" # optional default will be site title
    subtitle = "DataLad and git-annex showcase and hackathon"
    # imageUrl = "<img location>"
    # imageTitle = "my image"
    # imageWidth = 120
    # imageHeight = 120
