baseURL = 'https://distribits.live'
languageCode = 'en-us'
title = 'distribits'
theme = "PaperMod2"

# see https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

[params]
  [params.profileMode]
    enabled = true
    title = 'Technologies for distributed data management'
    # subtitle = "Supported by DataLad and git-annex"
    imageUrl = "pics/distribits_logo_a.svg"
    imageTitle = "distribits_logo"
    imageWidth = 800
  [[params.profileMode.buttons]]
    name = "🚀 Register"
    url = "/registration"
  [[params.profileMode.buttons]]
    name = "💡 About"
    url = "/about"
  [[params.profileMode.buttons]]
    name = "🔄 News"
    url = "/news"

  # repeat as many times as needed
  # icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
  [[params.socialIcons]]
    name = "mastodon"
    url = "https://fosstodon.org/@datalad"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/datalad"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/distribits"
