baseURL = 'https://datalad.github.io/distribits-2024-website/'
languageCode = 'en-us'
title = 'Distribits'
theme = "PaperMod"

# see https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

[params]
  [params.profileMode]
    enabled = true
    # title= "<Title>" # optional default will be site title
    subtitle = "DataLad and git-annex showcase and hackathon"
    # imageUrl = "<img location>"
    # imageTitle = "my image"
    # imageWidth = 120
    # imageHeight = 120

  # repeat as many times as needed
  # icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
  # [[params.socialIcons]]
  # name = "mastodon"
  # url = "https://fosstodon.org/@datalad"
